# Generated by Django 2.2 on 2020-01-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_text', models.CharField(max_length=500)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('index_in_sentence', models.IntegerField()),
                ('sentence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Sentence')),
            ],
        ),
    ]
